backend:
  name: git-gateway
  branch: master

media_folder: "/static/assets/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/static/assets/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "/posts/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Data de publicação", name: "date", widget: "date", format: "DD MM YY", required: true}
      - {label: "Imagem de capa", name: "thumbnail", widget: "image", required: false}
      - {label: "Editoria", name: "editorial", widget: "relation", collection: "editorials", searchFields: ["title"], valueField: "title", required: true}
      - {label: "Autor", name: "author", widget: "relation", collection: "authors", searchFields: ["title"], valueField: "title", required: false}
      - {label: "Corpo", name: "body", widget: "markdown", required: true}


  - name: "authors"
    label: "Autores"
    folder: "/data/authors"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    fields:
      - {label: "Nome", name: "title", widget: "string", required: true}
      - {label: "Foto (opcional)", name: "thumbnail", widget: "image", required: false}
      - {label: "Bio (opcional)", name: "body", widget: "markdown", required: false}
      - label: "Período atuando no Campus"
        name: "active"
        widget: "object"
        required: true
        fields:
          - {label: "Ano", name: "year", widget: "number", valueType: "int", min: 1980, max: 2080, default: 2018, required: true}
          - {label: "Semestre (0 ou 1)", name: "semester", widget: "select", options: ["0", "1"], required: true}


  - name: "editorials"
    label: "Editorias"
    folder: "/data/editorials"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    fields:
      - {label: "Nome da Editoria", name: "title", widget: "string", required: true}
      - {label: "Cor (hexadecimal)", name: "color", widget: "string", required: true, pattern: ["^#(?:[0-9a-fA-F]{3}){1,2}$", "Cor Inválida"]}
      - {label: "Descrição (opcional)", name: "title", widget: "string", required: true}
